// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoJtpXhzrXPTgJQNBXjlgvEsj3IEhIppo',
    appId: '1:1007592869470:web:80aa9bc5316bd045992ecf',
    messagingSenderId: '1007592869470',
    projectId: 'web-push-test-mhlee',
    authDomain: 'web-push-test-mhlee.firebaseapp.com',
    storageBucket: 'web-push-test-mhlee.firebasestorage.app',
    measurementId: 'G-445XZ9W6T0',
    databaseURL: 'https://web-push-test-mhlee-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6bptH_yjkHRJjR875V3yyHF6KASlBThA',
    appId: '1:1007592869470:android:2cf5dff0730e5873992ecf',
    messagingSenderId: '1007592869470',
    projectId: 'web-push-test-mhlee',
    storageBucket: 'web-push-test-mhlee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5ohDLD6Ww4KndvgWb5eMYx7nuqz0TzIM',
    appId: '1:1007592869470:ios:92b295436d22549f992ecf',
    messagingSenderId: '1007592869470',
    projectId: 'web-push-test-mhlee',
    storageBucket: 'web-push-test-mhlee.firebasestorage.app',
    iosBundleId: 'com.example.pushTestApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5ohDLD6Ww4KndvgWb5eMYx7nuqz0TzIM',
    appId: '1:1007592869470:ios:92b295436d22549f992ecf',
    messagingSenderId: '1007592869470',
    projectId: 'web-push-test-mhlee',
    storageBucket: 'web-push-test-mhlee.firebasestorage.app',
    iosBundleId: 'com.example.pushTestApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCoJtpXhzrXPTgJQNBXjlgvEsj3IEhIppo',
    appId: '1:1007592869470:web:939a025344e55ab5992ecf',
    messagingSenderId: '1007592869470',
    projectId: 'web-push-test-mhlee',
    authDomain: 'web-push-test-mhlee.firebaseapp.com',
    storageBucket: 'web-push-test-mhlee.firebasestorage.app',
    measurementId: 'G-G4H9SG2KZV',
  );
}
